import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';

import { useUser, login, logout } from '../lib/auth';

const Home: NextPage = () => {
    const user = useUser();

    const handleLogin = (): void => {
        login().catch((error) => console.error(error));
    };

    const handleLogout = (): void => {
        logout().catch((error) => console.error(error));
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Auth Example</h1>
                {user !== null ? <h2>ログインしている</h2> : <h2>ログインしていない</h2>}
                <button onClick={handleLogin}>ログイン</button>
                <button onClick={handleLogout}>ログアウト</button>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
